//! Bonds file parser (port of `util/BondsParser.scala`).
//!
//! The genesis ceremony uses a bonds file of `<public_key> <stake>` lines to set the initial
//! validator set.

use std::collections::BTreeMap;
use std::path::Path;

use rchain_crypto::public_key::PublicKey;
use rchain_crypto::signatures::secp256k1::Secp256k1;
use rchain_crypto::signatures::signatures_alg::SignaturesAlg;
use rchain_shared::base16;
use rchain_shared::refined::NonNegI64;

/// Parse a bonds file into a validator → stake map (port of `BondsParser.parse`).
pub fn parse(path: &Path) -> Result<BTreeMap<PublicKey, NonNegI64>, String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("FAILED PARSING BONDS FILE: {}\n{}", path.display(), e))?;
    let mut bonds = BTreeMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let (pk_str, stake_str) = line.split_once(' ').ok_or_else(|| {
            format!("INVALID LINE FORMAT: `<public_key> <stake>`, actual: `{line}`")
        })?;
        let pk_bytes =
            base16::decode(pk_str).ok_or_else(|| format!("INVALID PUBLIC KEY: `{pk_str}`"))?;
        let stake: i64 = stake_str.parse().map_err(|_| {
            format!("INVALID STAKE `{stake_str}`. Please put a non-negative number.")
        })?;
        let stake = NonNegI64::try_from(stake)
            .map_err(|_| format!("NEGATIVE STAKE `{stake_str}`. Stake must be non-negative."))?;
        bonds.insert(PublicKey::new(pk_bytes), stake);
    }
    Ok(bonds)
}

/// Parse a bonds file, generating a fresh validator set if the file does not exist (port of
/// `BondsParser.parse(path, autogenShardSize)`).
pub fn parse_or_generate(
    path: &Path,
    autogen_shard_size: i32,
) -> Result<BTreeMap<PublicKey, NonNegI64>, String> {
    match parse(path) {
        Ok(bonds) => Ok(bonds),
        Err(_) => new_validators(autogen_shard_size, path),
    }
}

/// Generate `autogen_shard_size` validators and write their keys + bonds file (port of
/// `newValidators`).
pub fn new_validators(
    autogen_shard_size: i32,
    bonds_file_path: &Path,
) -> Result<BTreeMap<PublicKey, NonNegI64>, String> {
    let mut bonds = BTreeMap::new();
    for i in 0..autogen_shard_size {
        let (sec, pub_key) = Secp256k1.new_key_pair();
        // Write `<public_key>.sk` file with the private key (owner-only perms: it is secret).
        //
        // **The write is checked** (C253's E4). It used to be `let _ = …`, so a ceremony that could
        // not write (a read-only directory, a full disk, a permissions mistake) produced no key file
        // and **no complaint**: the node came up with a validator key that does not exist on disk, and
        // the *next* boot generated a fresh one. That is the worst kind of ceremony failure — the node
        // looks healthy and its identity silently rotates.
        if let Some(parent) = bonds_file_path.parent() {
            let sk_file = parent.join(format!("{}.sk", base16::encode(pub_key.bytes())));
            rchain_crypto::util::key_util::write_private_key(
                &sk_file,
                base16::encode(sec.bytes()),
            )
            .map_err(|e| {
                format!(
                    "FAILED WRITING VALIDATOR KEY {}, so the key this node would bond with does not \
                     exist on disk and the next boot would generate a different one: {e}",
                    sk_file.display()
                )
            })?;
        }
        // `i >= 0`, so `i + 1 >= 1` is non-negative by construction.
        let stake = NonNegI64::try_from(i64::from(i) + 1)
            .map_err(|_| "autogenerated stake is non-negative".to_string())?;
        bonds.insert(pub_key, stake);
    }

    let mut content = String::new();
    for (pk, stake) in &bonds {
        content.push_str(&format!(
            "{} {}\n",
            base16::encode(pk.bytes()),
            i64::from(*stake)
        ));
    }
    // **And so is the bonds file itself** (C253's E4, the same site's other half). A discarded write
    // here means the ceremony produced no bonds file: the validator set it just generated exists only
    // in this process's memory, and the chain it starts cannot be rejoined by the node that started it.
    std::fs::write(bonds_file_path, content).map_err(|e| {
        format!(
            "FAILED WRITING BONDS FILE {}, so the validator set this ceremony generated exists only \
             in memory and the node cannot rejoin the chain it started: {e}",
            bonds_file_path.display()
        )
    })?;
    Ok(bonds)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_bonds_file() {
        let dir = std::env::temp_dir().join(format!("rchain-bonds-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bonds.txt");
        std::fs::write(
            &path,
            "04c591a8ff19ac9c4e4e5793673b83123437e975285e7b442f4ee2654dffca5e2d2103ed494718c697ac9aebcfd19612e224db46661011863ed2fc54e71861e2a6 100\n\
             04c591a8ff19ac9c4e4e5793673b83123437e975285e7b442f4ee2654dffca5e2d2103ed494718c697ac9aebcfd19612e224db46661011863ed2fc54e71861e2a6 200\n",
        )
        .unwrap();

        let bonds = parse(&path).unwrap();
        // Duplicate keys collapse to the last stake.
        assert_eq!(bonds.len(), 1);
        assert_eq!(
            bonds.values().next().copied(),
            Some(200.try_into().unwrap())
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn parses_bonds_file_rejects_bad_format() {
        let dir = std::env::temp_dir().join(format!("rchain-bonds-bad-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("bonds.txt");
        std::fs::write(&path, "garbage line without spaces\n").unwrap();

        assert!(parse(&path).is_err());

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// **A ceremony that cannot write its keys, or its bonds file, fails loudly and names the path**
    /// (C253's E4).
    ///
    /// Both writes used to discard their `Result` — `let _ = write_private_key(…)` and
    /// `let _ = std::fs::write(…)`. What that hid is not "a file is missing": it is that the node
    /// **comes up anyway**, bonded to a validator key that does not exist on disk, and the next boot
    /// generates a *different* one. The node looks healthy and its identity silently rotates, which is
    /// the worst shape a ceremony failure can take.
    ///
    /// So the falsifier asserts the loud failure *and* that the message carries the path, because an
    /// operator's next step is to look at it. Two cases, one per write, so the second write is not
    /// covered only by the first one's accident: a parent that is a **regular file** (the key write
    /// fails) and a bonds path that is a **directory** (the key write succeeds, the bonds write fails).
    #[test]
    fn a_ceremony_that_cannot_write_fails_loudly_and_names_the_path() {
        let dir =
            std::env::temp_dir().join(format!("rchain-bonds-unwritable-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        // (1) The parent is a regular file, so the `.sk` write cannot succeed.
        let blocker = dir.join("not-a-directory");
        std::fs::write(&blocker, b"a file, not a directory").unwrap();
        let err = new_validators(1, &blocker.join("bonds.txt"))
            .expect_err("no key file can be written under a regular file");
        assert!(
            err.contains("FAILED WRITING VALIDATOR KEY") && err.contains(".sk"),
            "the refusal names the step and the file: {err}"
        );

        // (2) The parent is writable, so the key write succeeds — and the bonds path is a directory,
        //     so the second write is the one that fails. This is the half a single case would miss.
        let second = dir.join("second");
        std::fs::create_dir_all(second.join("bonds.txt")).unwrap();
        let err = new_validators(1, &second.join("bonds.txt"))
            .expect_err("a bonds path that is a directory cannot be written");
        assert!(
            err.contains("FAILED WRITING BONDS FILE") && err.contains("bonds.txt"),
            "the refusal names the second write and its path: {err}"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }
}
